const $=s=>document.querySelector(s);const api='/_s3dir/api';let active='',editing=null;let toastTimer;
const els={buckets:$('#buckets'),bucketEmpty:$('#bucket-empty'),title:$('#objects-title'),crumb:$('#crumb'),loading:$('#loading'),error:$('#error'),errorMessage:$('#error-message'),empty:$('#object-empty'),table:$('#table-wrap'),rows:$('#object-rows'),upload:$('#upload'),uploadLabel:$('#upload-label'),deleteBucket:$('#delete-bucket'),dialog:$('#bucket-dialog'),name:$('#bucket-name'),formError:$('#bucket-form-error'),toast:$('#toast')};
const enc=s=>btoa(unescape(encodeURIComponent(s))).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');
const human=n=>n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`;
const tell=message=>{els.toast.textContent=message;els.toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>els.toast.classList.remove('show'),2600)};
async function request(url,options){const response=await fetch(url,options);if(!response.ok){let message=`Request failed (${response.status})`;try{message=(await response.json()).error||message}catch{}throw new Error(message)}return response}
function state(which,message=''){for(const el of [els.loading,els.error,els.empty,els.table])el.hidden=true;els[which].hidden=false;if(message)els.errorMessage.textContent=message}
async function loadBuckets(select){try{const data=await(await request(api)).json();els.buckets.replaceChildren();els.bucketEmpty.hidden=data.buckets.length>0;for(const b of data.buckets){const li=document.createElement('li'),button=document.createElement('button');button.type='button';button.innerHTML=`<span>${escapeHtml(b.name)}</span><small>${b.objects}</small>`;button.setAttribute('aria-current',b.name===active);button.onclick=()=>choose(b.name);li.append(button);els.buckets.append(li)}if(select)await choose(select);else if(!active&&data.buckets[0])await choose(data.buckets[0].name);else if(!data.buckets.length){active='';els.title.textContent='Choose a bucket';els.crumb.textContent='The files on disk appear here.';els.uploadLabel.hidden=true;els.deleteBucket.hidden=true;state('empty')}}catch(e){state('error',e.message)}}
async function choose(bucket){active=bucket;els.title.textContent=bucket;els.crumb.textContent=`./data/${bucket}/`;els.uploadLabel.hidden=false;els.deleteBucket.hidden=false;for(const b of els.buckets.querySelectorAll('button'))b.setAttribute('aria-current',b.querySelector('span').textContent===bucket);state('loading');try{const data=await(await request(`${api}/buckets/${encodeURIComponent(bucket)}`)).json();render(data.objects)}catch(e){state('error',e.message)}}
function render(objects){els.rows.replaceChildren();if(!objects.length){state('empty');return}for(const o of objects){const tr=document.createElement('tr');tr.tabIndex=0;const editable=/^(text\/|application\/(json|xml|javascript))/.test(o.content_type);tr.innerHTML=`<td>${escapeHtml(o.key)}</td><td>${escapeHtml(o.content_type)}</td><td>${human(o.size)}</td><td>${new Date(o.modified).toLocaleString()}</td><td><div class="row-actions">${editable?`<button class="edit" aria-label="Inspect and edit ${escapeAttr(o.key)}">✎</button>`:''}<a href="${api}/buckets/${encodeURIComponent(active)}/objects/${enc(o.key)}" download aria-label="Download ${escapeAttr(o.key)}">↓</a><button class="delete" aria-label="Delete ${escapeAttr(o.key)}">×</button></div></td>`;tr.querySelector('.delete').onclick=()=>removeObject(o.key);tr.querySelector('.edit')?.addEventListener('click',()=>openEditor(o));tr.onkeydown=e=>{const rows=[...els.rows.children],i=rows.indexOf(tr);if(e.key==='ArrowDown'){e.preventDefault();rows[Math.min(i+1,rows.length-1)].focus()}if(e.key==='ArrowUp'){e.preventDefault();rows[Math.max(i-1,0)].focus()}};els.rows.append(tr)}state('table')}
async function openEditor(object){try{const response=await request(`${api}/buckets/${encodeURIComponent(active)}/objects/${enc(object.key)}`);editing={...object,bucket:active};$('#editor-title').textContent=object.key;$('#editor-content').value=await response.text();$('#editor-error').textContent='';$('#editor-dialog').showModal();setTimeout(()=>$('#editor-content').focus(),0)}catch(e){tell(e.message)}}
async function removeObject(key){if(!confirm(`Delete “${key}” from ${active}? This also removes it from disk.`))return;try{await request(`${api}/buckets/${encodeURIComponent(active)}/objects/${enc(key)}`,{method:'DELETE'});tell(`Deleted ${key}`);await choose(active)}catch(e){tell(e.message)}}
$('#new-bucket').onclick=()=>{els.name.value='';els.formError.textContent='';els.dialog.showModal();setTimeout(()=>els.name.focus(),0)};$('#cancel-dialog').onclick=()=>els.dialog.close();$('#bucket-form').onsubmit=async e=>{e.preventDefault();if(!els.name.reportValidity())return;try{await request(`${api}/buckets`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:els.name.value})});const name=els.name.value;els.dialog.close();tell(`Created ${name}`);await loadBuckets(name)}catch(err){els.formError.textContent=err.message}};
async function uploadFiles(){const files=[...els.upload.files];if(!files.length)return;els.uploadLabel.textContent=`Uploading 0/${files.length}`;let uploaded=0;for(let i=0;i<files.length;i++){const f=files[i],key=f.webkitRelativePath||f.name;try{await request(`${api}/buckets/${encodeURIComponent(active)}/objects/${enc(key)}`,{method:'PUT',headers:{'content-type':f.type||'application/octet-stream'},body:f});uploaded++;els.uploadLabel.textContent=`Uploading ${uploaded}/${files.length}`}catch(e){tell(`${f.name}: ${e.message}`);break}}els.uploadLabel.innerHTML='Upload files<input id="upload" type="file" multiple>';els.upload=$('#upload');els.upload.onchange=uploadFiles;tell(`Uploaded ${uploaded} file${uploaded===1?'':'s'}`);await choose(active)}els.upload.onchange=uploadFiles;
els.deleteBucket.onclick=async()=>{if(!confirm(`Delete bucket “${active}”? It must be empty.`))return;try{await request(`${api}/buckets/${encodeURIComponent(active)}`,{method:'DELETE'});tell(`Deleted ${active}`);active='';await loadBuckets()}catch(e){tell(e.message)}};$('#retry').onclick=()=>active?choose(active):loadBuckets();
$('#cancel-editor').onclick=()=>$('#editor-dialog').close();$('#editor-form').onsubmit=async e=>{e.preventDefault();if(!editing)return;try{await request(`${api}/buckets/${encodeURIComponent(editing.bucket)}/objects/${enc(editing.key)}`,{method:'PUT',headers:{'content-type':editing.content_type},body:$('#editor-content').value});$('#editor-dialog').close();tell(`Saved ${editing.key}`);await choose(editing.bucket)}catch(err){$('#editor-error').textContent=err.message}};
function escapeHtml(v){const d=document.createElement('div');d.textContent=v;return d.innerHTML}function escapeAttr(v){return escapeHtml(v).replaceAll('"','&quot;')}
function online(){const off=!navigator.onLine;$('#offline').hidden=!off}addEventListener('online',online);addEventListener('offline',online);online();loadBuckets();
